[package]
name = "tour"
version = "0.1.0"
edition = "2021"

[package.metadata]

[package.metadata.ferrisup]
component_type = "minimal"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
